# Site settings
title: Diary of a .NET programmer
email: pbenetkiewicz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This blog is about programming in .NET. Some other languages and technologies may also sneak in.
baseurl: /blog
url: "http://benetkiewicz.github.io/blog/" # the base hostname & protocol for your site
twitter_username: pbenetkiewicz
github_username:  benetkiewicz
comments: true
# Build settings
markdown: kramdown
highlighter: rouge

theme: jekyll-theme-modernist